### ISSUE TITLE
v1.0.2 path to `main` is wrong

### ISSUE THREAD

**Issue by mmw** [steelsojka/lodash-decorators#13]
`package.json` has 

```
"main": "index.js",
```

should be

```
"main": "dist/index.js",
```

**Comment by mmw** [comment]
Or the build shouldn't be in `dist`... using a npm `prepublish` script would help to avoid this issue in the future if the build is done manually.

**Comment by izaakschroeder** [comment]
It also looks like there are reference's to ES6's `Reflect` in the code – there are no references to this on GitHub. This possibly means that you've published code from your local machine which is not yet on GitHub anywhere (or maybe babel is generating references to this but it's unlikely I imagine).

<img width="1211" alt="screen shot 2015-09-25 at 19 24 29" src="https://cloud.githubusercontent.com/assets/206921/10108837/29234768-6378-11e5-939a-e63e25b956d0.png">

Please make deployment part of your CI process to avoid this kind of thing. There is an excellent and simple guide here: http://docs.travis-ci.com/user/deployment/npm/ on how to automate all this.

**Comment by steelsojka** [comment]
@izaakschroeder  The Reflect call is intentional. It just needs to be documented that this requires the Reflect API (which if you are using a transpiler for ES2016 you are most likely using a polyfill anyways). This could also be switched to `Object.keys` as well. EDIT: I think I published the source instead... So ignore this comment ;)

@mmw I fudged with some of the package scripts when releasing 1.0.2. I must of screwed something up without noticing. Will fix it.

**Comment by steelsojka** [comment]
@mmw @izaakschroeder My bad. I published the source and not the staged package.

**Comment by steelsojka** [comment]
The right package should be published as v1.0.4 now.

**Comment by steelsojka** [comment]
@izaakschroeder I automated the deployment with travis instead of doing it mainly. Works great! Also, the Reflect API is not required as I have thought before. I was looking at an old build. Sorry for the confusion.

**Comment by mmw** [comment]
Thanks for your work maintaining the project @steelsojka! I just tested and we're looking good now :+1:
