### ISSUE TITLE
after using memoize decorator i can't use cache.size anymore

### ISSUE THREAD

**Issue by plandem** [steelsojka/lodash-decorators#18]
E.g.:

working, cache.size returns number:
```
import memoize from 'lodash/memoize';

class A {
	constructor() {
		this.f = memoize(this.f);
	}

	f = (item) => {
		if(this.f.cache.size > 10) {
			this.f.cache.clear();
		}

		return item;
	}
}
```

not working, cache.size is undefined:
```
import {memoize} from 'lodash-decorators';

class A {
	constructor() {
	}

	@memoize()
	f = (item) => {
		if(this.f.cache.size > 10) {
			this.f.cache.clear();
		}

		return item;
	}
}
```

**Comment by steelsojka** [comment]
This is not correct usage. Since memoize is an instance decorator, it replaces the method with a getter/setter which returns a memoized version of the function for that instance. Using this as a property decorator instead of a method decorator overwrites the getter and setter that is set on the descriptor. Why not code this as a method instead of a function expression?

```javascript
improt { memoize } from 'lodash-decorators';

class A {
  
  @memoize()
  f(item) {
    if (this.f.cache.size > 10) {
      this.f.cache.size.clear();
    }
    
    return item;
  }
}
```
