### ISSUE TITLE
multiple decorators not working

### ISSUE THREAD

**Issue by stepancar** [steelsojka/lodash-decorators#39]
see my fork https://github.com/stepancar/lodash-decorators/commit/64e7ab3ce03a5065a17eb86a7c5341d124e46ea6
added @autobind decorator.
should work correctly but emits error "SyntaxError: @autobind can only be used on functions, not: undefined"
```js
class MyClass {
       // should work
      @autobind
      @Debounce(10)
      fn() {
          calls++;
      }
}
```

**Comment by steelsojka** [comment]
This a caveat of using the library. Some decorators will not play nice with others. `Debounce` is applied to an instance and in order to do this it replaces the `value` in the descriptor with a getter/setter. This causes the `autobind` decorator to see a getter/setter .There's no standard for decorators applied to an instance. I'm pretty sure `autobind` does the exact same thing. You can either use `Bind` from this library  or bind in the constructor.
```javascript
class MyClass {
       // This works
      @Bind()
      @Debounce(10)
      fn() {
          calls++;
      }
}
```
