### ISSUE TITLE
Usage with arrow functions

### ISSUE THREAD

**Issue by O4epegb** [steelsojka/lodash-decorators#49]
Are decorators supposed to work with arrow functions as class properties?
I know that the spec is kinda vague, but some libraries (such as `mobx`) have decorators that works fine with arrow functions.

Example:

```
class Foo {
  @observable bar = '';

  // mobx decorator is working fine
  @action
  changeBar = value => {
    this.bar = value;
  }

  // lodash decorator is not working
  @throttle(500)
  onChangeHandler = e => {
    this.changeBar(e.target.value);
  }
}
```

**Comment by steelsojka** [comment]
Most of the decorators won't work with arrow functions. Since these are properties the value is not inferred. This will work with a class method. Some of the decorators work with properties, but not ones specific for methods.

```
class Foo {
  @observable bar = '';

  // mobx decorator is working fine
  @action
  changeBar = value => {
    this.bar = value;
  }

  // This will work
  @throttle(500)
  onChangeHandler(e) {
    this.changeBar(e.target.value);
  }
}
```

**Comment by O4epegb** [comment]
I wonder how mobx decorators work then!

**Comment by steelsojka** [comment]
@O4epegb Decorators work on properties. Several lodash decorators work on properties. In your case, throttle does not. This is by design. There is not a clear way to get the initialized value to wrap it with throttle functionality. I have never used mobx, but it is most likely storing metadata about the property and then using that metadata to mutate the property as part of its lifecycle.
