### ISSUE TITLE
Why not memoize on getter

### ISSUE THREAD

**Issue by artmadeit** [steelsojka/lodash-decorators#55]
First of all...really excellent repo! 😄 

It seems to me that it will be nice if  `@Memoize` could work with getters

```ts
@Memoize()
 get total() {
    return sum(orderLines.map(x => x.priceUnit * x.quantity))
 }
```

It just as a simple change on Memoize decorator:
https://github.com/steelsojka/lodash-decorators/blob/master/src/memoize.ts#L37

to accept `{ getter: true,  optionalParams: true }` as DecoratorConfigOptions.
This is just a recommendation, will be happy if you'll add it!

**Comment by steelsojka** [comment]
@artmadeit Memoize doesn't really make sense on a getter since it doesn't take any arguments. Memoize returns a previous result based on arguments received. Since it takes no arguments it would only ever return a value once.  The only way I could see this useful is if you supplied a resolver that returned the key to store the results under, like when the length of orderLines has changed.

```typescript
@Memoize('getOrderLinesLength')
get total(): number {
   return sum(orderLines.map(x => x.priceUnit * x.quantity))
}

getOrderLinesLength(): number {
  return this.orderLines.length;
}
```

**Comment by steelsojka** [comment]
@artmadeit Also, note that with the latest decorator spec the above will no longer be possible as we won't have access to the prototype anymore at decoration time.

**Comment by artmadeit** [comment]
@steelsojka thanks for your response, I currently using in the same way as your comment, with `getOrderLinesLength()` and `getTotal()` method.

I just say it will be nicer if it could be used with get properties.
Thanks = 😄
