### ISSUE TITLE
@memoize() does not cache getters

### ISSUE THREAD

**Issue by IStranger** [steelsojka/lodash-decorators#56]
Hi. Thanks for the great package. It is very useful for personal productivity. 
However, I've found some strange behavior: `@memoize()` does not cache getter result. 
I've not understood, it is a bug or a feature :)

```js
class TestClass {

    @memoize()
    someMethod() {
        console.log('someMethod()');
        return 1;
    }

    @memoize()
    get someGetter() {
        console.log('someGetter()');
        return 2;
    }
}

// Debug
const testObject = new TestClass();

console.log(testObject.someMethod());
console.log(testObject.someMethod());
console.log(testObject.someMethod());

console.log(testObject.someGetter);
console.log(testObject.someGetter);
console.log(testObject.someGetter);
```

It will show in console:
```
someMethod()
    1
    1
    1
someGetter()
    2
someGetter()
    2
someGetter()
    2
```

(Angular 7.2, Typescript 3.2.2, FF 63)

**Comment by steelsojka** [comment]
@IStranger This isn't how it should work. Memoization caches based on the parameters received. A getter has no parameters so there is no way to cache the results. You are better off proxying to a function that accepts some parameters to memoize from.

```javascript
get something() {
  return this.getSomething(this.someValue);
}

@Memoize()
getSomething(someValue) {
  // Do some stuff
}
```
What you may be looking more for is the Once decorator since your functions will only ever be called once.

**Comment by IStranger** [comment]
@steelsojka  Thank you for the alternatives. However, getter is not a function :)
For example, you can replace getter by regular property (and vice versa) without refactoring all the usages. 
Moreover, typical convention requires use `object.getMyProperty()` and `object.myProperty`. I prefer the second one. 

> A getter has no parameters so there is no way to cache the results.

Do you mean there is no technical possibility?

**Comment by eamodio** [comment]
@steelsojka I just got bitten by this issue too. Could we use the name of the property as the key for getters since they can't have parameters? What is done today to handle parameterless functions? Could the same be done? IMO, memoizing a getter is just as valuable as memoizing a function.

Related, if the decorators won't work when applying them they (imo) should throw -- e.g. if @memoize can't be applied to a `get` then it should throw an error

**Comment by jscharett** [comment]
I tried using `@Once` on my getter, as suggested, but it did not seem to work either.  Getter continually gets called.  Am I missing something?

**Comment by jscharett** [comment]
Does Once support getters?
```js
export const Once = DecoratorFactory.createInstanceDecorator(
  new DecoratorConfig(once, new PreValueApplicator(), { setter: true, optionalParams: true })
) as BiTypedDecorator;
```

**Comment by GerkinDev** [comment]
Hi there,

For my own needs, I need to investigate this issue. Unfortunatelly, this repo has been inactive for quite some time, and the owner seems very busy. I hope @steelsojka will find some time to reply.

**Comment by pies** [comment]
Very annoying issue, I use memoized getters a lot to implement singletons.

**Comment by steelsojka** [comment]
@GerkinDev I haven't had time to maintain this package. It's technically feature complete for it's use case.

@pies Memoize is not designed to work on getters. See my comment above about caching.

**Comment by pies** [comment]
Thanks, I've simply switched to a different library (memoized-class-decorator) that has that feature. Thank you for responding!
